version: '3.9'
services:
    soap:
        build: .
        env_file:
            - .env
            - ../.env
        environment:
            - DB_HOST=host.docker.internal
        depends_on:
            - db
        ports:
            - ${APP_PORT:-8081}:8080
    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASS:?No password set}
            - MYSQL_DATABASE=${DB_NAME:-binotify-soap}
            - MYSQL_USER=${DB_USER:-binotify-soap-user}
            - MYSQL_PASSWORD=${DB_PASS:?No password set}
        ports:
            - ${DB_PORT:-3306}:3306
